class_0 = [
    "grinning face",
    "smiling face with open mouth",
    "winking face",
    "robot face",
    "smiling cat face with open mouth",
    "superhero",
    "man superhero",
    "man superhero light skin tone",
    "man superhero medium light skin tone",
    "grinning cat face with smiling eyes",
    "man superhero medium skin tone",
    "man superhero dark skin tone",
    "man superhero medium dark skin tone",
    "woman superhero",
    "woman superhero light skin tone",
    "woman superhero medium light skin tone",
    "woman superhero medium skin tone",
    "woman superhero dark skin tone",
    "woman superhero medium dark skin tone",
    "supervillain",
    "cat face with tears of joy",
    "man supervillain",
    "man supervillain light skin tone",
    "man supervillain medium light skin tone",
    "man supervillain medium skin tone",
    "man supervillain medium dark skin tone",
    "smiling cat face with heart shaped eyes",
    "man supervillain dark skin tone",
    "woman supervillain",
    "woman supervillain light skin tone",
    "woman supervillain medium light skin tone",
    "woman supervillain medium skin tone",
    "woman supervillain medium dark skin tone",
    "woman supervillain dark skin tone",
    "mage",
    "cat face with wry smile",
    "man mage",
    "man mage light skin tone",
    "man mage medium light skin tone",
    "man mage medium skin tone",
    "man mage medium dark skin tone",
    "man mage dark skin tone",
    "woman mage",
    "kissing cat face with closed eyes",
    "woman mage light skin tone",
    "woman mage medium light skin tone",
    "woman mage medium skin tone",
    "woman mage medium dark skin tone",
    "woman mage dark skin tone",
    "weary cat face",
    "crying cat face",
    "vampire",
    "man vampire",
    "pouting cat face",
    "man vampire light skin tone",
    "man vampire medium light skin tone",
    "man vampire medium skin tone",
    "man vampire medium dark skin tone",
    "man vampire dark skin tone",
    "woman vampire",
    "woman vampire light skin tone",
    "woman vampire medium light skin tone",
    "woman vampire medium skin tone",
    "woman vampire medium dark skin tone",
    "smiling face with smiling eyes",
    "see no evil monkey",
    "woman vampire dark skin tone",
    "hear no evil monkey",
    "elf",
    "speak no evil monkey",
    "man elf",
    "man elf light skin tone",
    "man elf medium light skin tone",
    "man elf medium skin tone",
    "man elf medium dark skin tone",
    "man elf dark skin tone",
    "woman elf",
    "woman elf light skin tone",
    "woman elf medium light skin tone",
    "woman elf medium skin tone",
    "woman elf medium dark skin tone",
    "woman elf dark skin tone",
    "zombie",
    "man zombie",
    "woman zombie",
    "face massage",
    "man getting face massage",
    "man getting face massage type 1 2",
    "man getting face massage type 3",
]

class_1 = [
    "man getting face massage type 4",
    "man getting face massage type 5",
    "man getting face massage type 6",
    "woman getting face massage",
    "woman getting face massage type 1 2",
    "woman getting face massage type 3",
    "woman getting face massage type 4",
    "woman getting face massage type 5",
    "woman getting face massage type 6",
    "haircut",
    "man getting haircut",
    "man getting haircut type 1 2",
    "man getting haircut type 3",
    "man getting haircut type 4",
    "man getting haircut type 5",
    "man getting haircut type 6",
    "woman getting haircut",
    "woman getting haircut type 1 2",
    "woman getting haircut type 3",
    "woman getting haircut type 4",
    "woman getting haircut type 5",
    "woman getting haircut type 6",
    "smiling face with halo",
    "smiling face with smiling eyes and three hearts",
    "smiling face with heart shaped eyes",
    "juggling",
    "man juggling",
    "man juggling type 1 2",
    "man juggling type 3",
    "man juggling type 4",
    "man juggling type 5",
    "man juggling type 6",
    "woman juggling",
    "woman juggling type 1 2",
    "woman juggling type 3",
    "woman juggling type 4",
    "woman juggling type 5",
    "woman juggling type 6",
    "grinning face with star eyes",
    "monkey face",
    "dog face",
    "wolf face",
    "fox face",
    "cat face",
    "lion face",
    "tiger face",
    "horse face",
    "unicorn face",
    "zebra face",
    "cow face",
    "pig face",
    "face throwing a kiss",
    "giraffe face",
    "mouse face",
    "hamster face",
    "rabbit face",
    "bear face",
    "panda face",
    "frog face",
    "dragon face",
    "kissing face",
    "white smiling face",
    "kissing face with closed eyes",
    "clock face twelve oclock",
    "clock face twelve thirty",
    "clock face one oclock",
    "clock face one thirty",
    "clock face two oclock",
    "clock face two thirty",
    "clock face three oclock",
    "clock face three thirty",
    "clock face four oclock",
    "clock face four thirty",
    "clock face five oclock",
    "clock face five thirty",
    "clock face six oclock",
    "clock face six thirty",
    "clock face seven oclock",
    "clock face seven thirty",
    "clock face eight oclock",
    "clock face eight thirty",
    "clock face nine oclock",
    "clock face nine thirty",
    "clock face ten oclock",
    "clock face ten thirty",
    "clock face eleven oclock",
    "clock face eleven thirty",
    "new moon with face",
    "first quarter moon with face",
    "last quarter moon with face",
    "full moon with face",
    "sun with face",
    "wind blowing face",
    "smiling face with open mouth and smiling eyes",
    "kissing face with smiling eyes",
    "face savouring delicious food",
    "face with stuck out tongue",
    "face with stuck out tongue and winking eye",
    "grinning face with one large and one small eye",
    "face with stuck out tongue and tightly closed eyes",
    "money mouth face",
    "hugging face",
    "smiling face with smiling eyes and hand covering mouth",
]
